#Fill here the Google Maps API keys for your application
#In this sample:
#For development and test, we have only one possible host (localhost:3000), so there is only a single key associated with the mode.
#In production, the app can be accessed through 2 different hosts: thepochisuperstarmegashow.com and exmaple.com. There then needs a 2-key hash. If you deployed to one host, only the API key would be needed (as in development and test).

development: ABQIAAAAFqvIR95wxQmyGiyuZvNbHRQnes9Ynq7B92XIZI7_IcEnoLAezRQ9lnEfudQioBoi0jPXHfxpBIJ34w
#  127.0.0.1:     ABQIAAAAFqvIR95wxQmyGiyuZvNbHRT2yXp_ZAY8_ufC3CFXhHIE1NvwkxQZ7KGgcIiP20GUMVEGIWu9m1MifQ
#  localhost:     ABQIAAAAFqvIR95wxQmyGiyuZvNbHRT2yXp_ZAY8_ufC3CFXhHIE1NvwkxQZ7KGgcIiP20GUMVEGIWu9m1MifQ
#  riclife.local: ABQIAAAAFqvIR95wxQmyGiyuZvNbHRQnes9Ynq7B92XIZI7_IcEnoLAezRQ9lnEfudQioBoi0jPXHfxpBIJ34w

test:
  ABQIAAAAFqvIR95wxQmyGiyuZvNbHRQnes9Ynq7B92XIZI7_IcEnoLAezRQ9lnEfudQioBoi0jPXHfxpBIJ34w

production:
  ABQIAAAAFqvIR95wxQmyGiyuZvNbHRTgLH10JdzHMf9Z6LO7XFh7hux4EBRW3sS85tj9i8njWzSQmFMYul5dVw

# riclife.palladius.eu: ABQIAAAAFqvIR95wxQmyGiyuZvNbHRTgLH10JdzHMf9Z6LO7XFh7hux4EBRW3sS85tj9i8njWzSQmFMYul5dVw
#  riclife.palladius.eu: ABQIAAAAFqvIR95wxQmyGiyuZvNbHRTgLH10JdzHMf9Z6LO7XFh7hux4EBRW3sS85tj9i8njWzSQmFMYul5dVw
